version: "3"
services:
  ldap-server:
    image: osixia/openldap:latest
    restart: always
    container_name: ldap-host
    environment:
      LDAP_ORGANISATION: "ABC"
      LDAP_DOMAIN: "dev.local"
      LDAP_ADMIN_PASSWORD: "admin"
    volumes:
      - "./ldif:/ldif"
      - "data:/var/lib/ldap"
      - "config:/etc/ldap/slapd.d"
    ports:
      - "389:389"
  
  ldap-admin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-admin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "6001:80"
    links:
      - "ldap-server:ldap"
    volumes:
      - "phpadmin_data:/var/www/phpldapadmin"

volumes:
  data:
  config:
  phpadmin_data:
